services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"   # Selenium WebDriver port
      - "7900:7900"   # VNC viewer port (optional, to see browser UI)
    shm_size: 2gb     # Fix "Chrome crashed" errors in Docker

  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongodb
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongo-data:/data/db

  # mongo-express:
  #   image: mongo-express:1.0.0-alpha.4
  #   container_name: mongo-express
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_SERVER: mongodb


  # backend:
  #   build: ./backend
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - NODE_ENV=development

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  
# volumes:
#   mongo-data: